const mix1Artists = [
  "100 Gecs",
  "AJR",
  "Akon",
  "All American Rejects",
  "Aloe Blacc",
  "Andy Grammer",
  "Avicii",
  "Bee Gees",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Camila Cabello",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "Chumbawamba",
  "DaBaby",
  "Drake",
  "Dua Lipa",
  "Elton John",
  "Fifth Harmony",
  "Flume",
  "Frank Ocean",
  "Franz Ferdinand",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Green Day",
  "Janis Joplin",
  "Jason Derulo",
  "Jeremy Zucker",
  "Journey",
  "Justin Bieber",
  "Katy Perry",
  "Kelly Clarkson",
  "Kesha",
  "Khalid",
  "Maroon 5",
  "Lil Dicky",
  "Lil Uzi Vert",
  "Lil Wayne",
  "Lizzo",
  "Loote",
  "Marshmello",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Pink",
  "Post Malone",
  "Rick Springfield",
  "Sean Paul",
  "Sia",
  "Simple Plan",
  "Sum 41",
  "Survivor",
  "The Beatles",
  "Tom Petty",
  "Trevor Daniel",
  "Weezer",
];

const mix2Artists = [
  "100 Gecs",
  "AJ Mitchell",
  "AJR",
  "Akon",
  "All American Rejects",
  "Aloe Blacc",
  "Andy grammer",
  "Avicii",
  "Big Sean",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Camila Cabello",
  "Cardi B",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "Chumbawamba",
  "DaBaby",
  "Drake",
  "Dua Lipa",
  "Eminem",
  "Fifth Harmony",
  "Flume",
  "Frank Ocean",
  "G Eazy",
  "Galantis",
  "Green Day",
  "Jason Derulo",
  "Jay Sean",
  "Jeremy Zucker",
  "Journey",
  "Justin Bieber",
  "Katy Perry",
  "Kelly Clarkson",
  "Kesha",
  "Khalid",
  "Maroon 5",
  "Lil Aaron",
  "Lil Dicky",
  "Lil Wayne",
  "Lizzo",
  "Loote",
  "Marshmello",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Owl City",
  "Pink",
  "Post Malone",
  "Sean Paul",
  "Sia",
  "Snoop Dogg",
  "Sum 41",
  "Survivor",
  "SZA",
  "Timeflies",
  "Travis Scott",
  "Trevor Daniel",
  "Ty Dolla Sign",
  "Weezer",
  "Wiz Khalifa",
  "YBN Nahmir",
];

const mix3Artists = [
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Andy Grammer",
  "Avicii",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Call Me Karizma",
  "Camila Cabello",
  "Cardi B",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "Cyndi Lauper",
  "DaBaby",
  "Drake",
  "Dua Lipa",
  "Elton John",
  "Eminem",
  "Frank Ocean",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Green Day",
  "Janis Joplin",
  "Jason Derulo",
  "Jeremy Zucker",
  "Journey",
  "Katy Perry",
  "Kesha",
  "Khalid",
  "Lil Dicky",
  "Lil Peep",
  "Lil Uzi Vert",
  "Lil Wayne",
  "Lizzo",
  "Lucas & Steve",
  "Marc E Bassy",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Notorious BIG",
  "Owl City",
  "Pink",
  "Post Malone",
  "Rick Springfield",
  "Sean Paul",
  "Simple Plan",
  "Survivor",
  "T-Pain",
  "The Beatles",
  "Tom Petty",
  "Travis Scott",
  "Trevor Daniel",
  "Ty Dolla Sign",
  "Wallpaper.",
  "Weezer",
];

const mix4Artists = [
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Bee Gees",
  "Big Sean",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Camila Cabello",
  "Cardi B",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "DaBaby",
  "David Guetta",
  "Drake",
  "Eminem",
  "Frank Ocean",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "J Cole",
  "Janis Joplin",
  "Jason Derulo",
  "Jeremy Zucker",
  "Journey",
  "Justin Bieber",
  "Kanye West",
  "Katy Perry",
  "Khalid",
  "Kyle",
  "Lil Dicky",
  "Lil Wayne",
  "Loote",
  "Marshmello",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Notorious BIG",
  "Owl City",
  "Pink",
  "Post Malone",
  "Sean Paul",
  "Snoop Dogg",
  "Sum 41",
  "Survivor",
  "The Beatles",
  "Tove Lo",
  "Ty Dolla Sign",
  "Wallpaper.",
  "The Weeknd",
  "Weezer",
  "Wiz Khalifa",
  "YBN Nahmir",
];

const mix5Artists = [
  "AJR",
  "Akon",
  "Aloe Blacc",
  "Andy Grammer",
  "Avicii",
  "Bebe Rexha",
  "Big Sean",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Call Me Karizma",
  "Calvin Harris",
  "Camila Cabello",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "Convolk",
  "DaBaby",
  "David Guetta",
  "Demi Lovato",
  "Drake",
  "Dua Lipa",
  "Elton John",
  "Eminem",
  "Flume",
  "Frank Ocean",
  "Franz Ferdinand",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Green Day",
  "Jason Derulo",
  "Jeremy Zucker",
  "Katy Perry",
  "Kesha",
  "Khalid",
  "Lil Aaron",
  "Lil Wayne",
  "Loote",
  "Loud Luxury",
  "Lucas & Steve",
  "Maroon 5",
  "Marshmello",
  "Martin Garrix",
  "Notorious BIG",
  "Owl City",
  "Pink",
  "Post Malone",
  "Rolling Stones",
  "Sia",
  "Snoop Dogg",
  "Sum 41",
  "T-Pain",
  "The Beatles",
  "Tom Petty",
  "Travis Scott",
  "Weezer",
  "Wiz Khalifa",
];

const mix8Artists = [
  "50 Cent",
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Avicii",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Camila Cabello",
  "Cardi B",
  "Chainsmokers",
  "Chance The Rapper",
  "Cheat Codes",
  "Clean Bandit",
  "Creedence Clearwater Revival",
  "DaBaby",
  "Drake",
  "Eminem",
  "Future",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Iamsu",
  "J Cole",
  "Jason Derulo",
  "Jay Sean",
  "Jeremy Zucker",
  "Justin Bieber",
  "Katy Perry",
  "Kesha",
  "Kid Cudi",
  "KYLE",
  "Lil Aaron",
  "Lil Pump",
  "Lil Uzi Vert",
  "Lil Wayne",
  "Lil Yachty",
  "Loote",
  "Loud Luxury",
  "Lucas & Steve",
  "Machine Gun Kelly",
  "Martin Garrix",
  "Michael Jackson",
  "NOTD",
  "Notorious BIG",
  "P-Lo",
  "Pink",
  "Post Malone",
  "Sean Paul",
  "Sia",
  "Snoop Dogg",
  "SZA",
  "The Weeknd",
  "Tom Petty",
  "Travis Scott",
  "Trevor Daniel",
  "Trinidad James",
  "Usher",
  "Wiz Khalifa",
  "YBN Nahmir",
  "Yo Gotti",
];

const mix10Artists = [
  "100 Gecs",
  "3Oh!3",
  "50 Cent",
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Anderson Paak",
  "Ariana Grande",
  "Avicii",
  "Blackbear",
  "Blink 182",
  "Camila Cabello",
  "Creedence Clearwater Revival",
  "Chainsmokers",
  "Cheat Codes",
  "Clean Bandit",
  "Elton John",
  "Eminem",
  "Fetty Wap",
  "Flume",
  "Frank Ocean",
  "Future",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Green Day",
  "Illenium",
  "J Cole",
  "Jay Sean",
  "Kanye West",
  "Kesha",
  "Kygo",
  "Lauv",
  "Lil Aaron",
  "Lil Pump",
  "Lil Wayne",
  "Lil Yachty",
  "Loote",
  "Mac Miller",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Michael Jackson",
  "Mike Williams",
  "NOTD",
  "Notorious BIG",
  "Owl City",
  "Post Malone",
  "The Proclaimers",
  "Rihanna",
  "Sage The Gemini",
  "Selena Gomez",
  "Shakira",
  "Sia",
  "Tom Petty",
  "Travis Scott",
  "Usher",
  "Yo Gotti",
  "Young Dro",
];

const mix11Artists = [
  "100 Gecs",
  "50 Cent",
  "AJR",
  "Aloe Blacc",
  "Anderson Paak",
  "Ariana Grande",
  "Avicii",
  "Backstreet Boys",
  "Bastille",
  "Bebe Rexha",
  "Black Eyed Peas",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Creedence Clearwater Revival",
  "Chainsmokers",
  "Chance The Rapper",
  "Charlie XCX",
  "Cher",
  "Chris Brown",
  "Chumbawamba",
  "Cyndi Lauper",
  "Clean Bandit",
  "Cobra Starship",
  "DaBaby",
  "DJ Snake",
  "Drake",
  "Dua Lipa",
  "Eminem",
  "Felix Jaehn",
  "Fetty Wap",
  "Fifth Harmony",
  "Galantis",
  "Goody Grace",
  "J Cole",
  "Jason Derulo",
  "Jeremy Zucker",
  "Journey",
  "Kanye West",
  "Katy Perry",
  "Kesha",
  "Khalid",
  "Kygo",
  "Lady Gaga",
  "Lil Dicky",
  "Lil Peep",
  "Lil Yachty",
  "Lizzo",
  "Loud Luxury",
  "Louis The Child",
  "LZRD",
  "Mac Miller",
  "Major Lazer",
  "Martin Garrix",
  "Martin Solveig",
  "Machine Gun Kelly",
  "Michael Jackson",
  "Mike Posner",
  "NOTD",
  "P-Lo",
  "Post Malone",
  "Preme",
  "Quinn XCII",
  "Rihanna",
  "Sam Feldt",
  "Sean Paul",
  "Sia",
  "Social House",
  "Survivor",
  "The Wanted",
  "The Weeknd",
  "Tiesto",
  "Tom Petty",
  "Tones & I",
  "Tove Lo",
  "Travis Scott",
  "Ty Dolla Sign",
  "Uncle Kracker",
  "Usher",
  "Yo Gotti",
];

const mix12Artists = [
  "24kGoldn",
  "50 Cent",
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Anderson Paak",
  "Astrid S",
  "Avicii",
  "Bastille",
  "Bebe Rexha",
  "Billie Eilish",
  "Black Eyed Peas",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Cardi B",
  "Chainsmokers",
  "Chance The Rapper",
  "Charlie XCX",
  "Cheat Codes",
  "Cher",
  "Chris Brown",
  "David Guetta",
  "Diana Ross",
  "Drake",
  "Dua Lipa",
  "Eiffel 65",
  "Fifth Harmony",
  "G Eazy",
  "Galantis",
  "Green Day",
  "Iamsu",
  "Illenium",
  "Jason Derulo",
  "Jay Sean",
  "Kanye West",
  "Katy Perry",
  "Khalid",
  "Kid Cudi",
  "Kid Ink",
  "Lil Pump",
  "Lil Uzi Vert",
  "Lil Wayne",
  "Lil Yachty",
  "Loote",
  "Louis The Child",
  "Lucas & Steve",
  "LZRD",
  "Martin Garrix",
  "Michael Jackson",
  "Nicki Minaj",
  "NOTD",
  "Owl City",
  "Post Malone",
  "Preme",
  "Rihanna",
  "Sam Feldt",
  "Sum 41",
  "The Beatles",
  "Topic",
  "Travis Scott",
  "Trinidad James",
  "Ty Dolla Sign",
  "Weezer",
  "Wiz Khalifa",
];

const mix13Artists = [
  "3Oh!3",
  "50 Cent",
  "Aloe Blacc",
  "Anderson Paak",
  "Andy Grammer",
  "Avicii",
  "Bastille",
  "The Beatles",
  "Bebe Rexha",
  "Bruno Mars",
  "Bryce Vine",
  "Call Me Karizma",
  "Camila Cabello",
  "Chainsmokers",
  "Chance The Rapper",
  "Charlie XCX",
  "Cheat Codes",
  "Chris Brown",
  "Clean Bandit",
  "Cobra Starship",
  "Diana Ross",
  "Ed Sheeran",
  "Eiffel 65",
  "Eminem",
  "Fetty Wap",
  "Galantis",
  "Green Day",
  "Iamsu",
  "J Cole",
  "Jason Derulo",
  "Kanye West",
  "Katy Perry",
  "Kesha",
  "Kygo",
  "Lady Gaga",
  "Lil Pump",
  "Lil Wayne",
  "Lil Yachty",
  "Lizzo",
  "Loote",
  "Louis The Child",
  "Lukas Graham",
  "Makeout",
  "Maroon 5",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Migos",
  "Mike Posner",
  "Nicki Minaj",
  "NOTD",
  "Owl City",
  "P-Lo",
  "Pink",
  "Post Malone",
  "Pusha T",
  "Quavo",
  "Quinn XCII",
  "Sam Feldt",
  "T-Pain",
  "The Beatles",
  "The Him",
  "The Neighbourhood",
  "The Proclaimers",
  "Tones & I",
  "Topic",
  "Travis Scott",
  "Trinidad James",
  "Uncle Kracker",
  "Wallpaper.",
  "Wiz Khalifa",
];

const mix1 = {
  title: "mix1",
  artists: mix1Artists,
};
const mix2 = {
  title: "mix2",
  artists: mix2Artists,
};
const mix3 = {
  title: "mix3",
  artists: mix3Artists,
};
const mix4 = {
  title: "mix4",
  artists: mix4Artists,
};
const mix5 = {
  title: "mix5",
  artists: mix5Artists,
};
const mix8 = {
  title: "mix8",
  artists: mix8Artists,
};
const mix10 = {
  title: "mix10",
  artists: mix10Artists,
};
const mix11 = {
  title: "mix11",
  artists: mix11Artists,
};
const mix12 = {
  title: "mix12",
  artists: mix12Artists,
};
const mix13 = {
  title: "mix13",
  artists: mix13Artists,
};

export const mixes = [
  mix1,
  mix2,
  mix3,
  mix4,
  mix5,
  mix8,
  mix10,
  mix11,
  mix12,
  mix13,
];
