const mix1Artists = [
  "100 Gecs",
  "AJR",
  "Akon",
  "All American Rejects",
  "Aloe Blacc",
  "Andy Grammer",
  "Avicii",
  "Bee Gees",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Camila Cabello",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "Chumbawamba",
  "DaBaby",
  "Drake",
  "Dua Lipa",
  "Elton John",
  "Fifth Harmony",
  "Flume",
  "Frank Ocean",
  "Franz Ferdinand",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Green Day",
  "Janis Joplin",
  "Jason Derulo",
  "Jeremy Zucker",
  "Journey",
  "Justin Bieber",
  "Katy Perry",
  "Kelly Clarkson",
  "Kesha",
  "Khalid",
  "Maroon 5",
  "Lil Dicky",
  "Lil Uzi Vert",
  "Lil Wayne",
  "Lizzo",
  "Loote",
  "Marshmello",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Pink",
  "Post Malone",
  "Rick Springfield",
  "Sean Paul",
  "Sia",
  "Simple Plan",
  "Sum 41",
  "Survivor",
  "The Beatles",
  "Tom Petty",
  "Trevor Daniel",
  "Weezer",
];

const mix2Artists = [
  "100 Gecs",
  "AJ Mitchell",
  "AJR",
  "Akon",
  "All American Rejects",
  "Aloe Blacc",
  "Andy grammer",
  "Avicii",
  "Big Sean",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Camila Cabello",
  "Cardi B",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "Chumbawamba",
  "DaBaby",
  "Drake",
  "Dua Lipa",
  "Eminem",
  "Fifth Harmony",
  "Flume",
  "Frank Ocean",
  "G Eazy",
  "Galantis",
  "Green Day",
  "Jason Derulo",
  "Jay Sean",
  "Jeremy Zucker",
  "Journey",
  "Justin Bieber",
  "Katy Perry",
  "Kelly Clarkson",
  "Kesha",
  "Khalid",
  "Maroon 5",
  "Lil Aaron",
  "Lil Dicky",
  "Lil Wayne",
  "Lizzo",
  "Loote",
  "Marshmello",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Owl City",
  "Pink",
  "Post Malone",
  "Sean Paul",
  "Sia",
  "Snoop Dogg",
  "Sum 41",
  "Survivor",
  "SZA",
  "Timeflies",
  "Travis Scott",
  "Trevor Daniel",
  "Ty Dolla Sign",
  "Weezer",
  "Wiz Khalifa",
  "YBN Nahmir",
];

const mix3Artists = [
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Andy Grammer",
  "Avicii",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Call Me Karizma",
  "Camila Cabello",
  "Cardi B",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "Cyndi Lauper",
  "DaBaby",
  "Drake",
  "Dua Lipa",
  "Elton John",
  "Eminem",
  "Frank Ocean",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Green Day",
  "Janis Joplin",
  "Jason Derulo",
  "Jeremy Zucker",
  "Journey",
  "Katy Perry",
  "Kesha",
  "Khalid",
  "Lil Dicky",
  "Lil Peep",
  "Lil Uzi Vert",
  "Lil Wayne",
  "Lizzo",
  "Lucas & Steve",
  "Marc E Bassy",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Notorious BIG",
  "Owl City",
  "Pink",
  "Post Malone",
  "Rick Springfield",
  "Sean Paul",
  "Simple Plan",
  "Survivor",
  "T-Pain",
  "The Beatles",
  "Tom Petty",
  "Travis Scott",
  "Trevor Daniel",
  "Ty Dolla Sign",
  "Wallpaper.",
  "Weezer",
];

const mix4Artists = [
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Bee Gees",
  "Big Sean",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Camila Cabello",
  "Cardi B",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "DaBaby",
  "David Guetta",
  "Drake",
  "Eminem",
  "Frank Ocean",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "J Cole",
  "Janis Joplin",
  "Jason Derulo",
  "Jeremy Zucker",
  "Journey",
  "Justin Bieber",
  "Kanye West",
  "Katy Perry",
  "Khalid",
  "Kyle",
  "Lil Dicky",
  "Lil Wayne",
  "Loote",
  "Marshmello",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Notorious BIG",
  "Owl City",
  "Pink",
  "Post Malone",
  "Sean Paul",
  "Snoop Dogg",
  "Sum 41",
  "Survivor",
  "The Beatles",
  "Tove Lo",
  "Ty Dolla Sign",
  "Wallpaper.",
  "The Weeknd",
  "Weezer",
  "Wiz Khalifa",
  "YBN Nahmir",
];

const mix5Artists = [
  "AJR",
  "Akon",
  "Aloe Blacc",
  "Andy Grammer",
  "Avicii",
  "Bebe Rexha",
  "Big Sean",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Call Me Karizma",
  "Calvin Harris",
  "Camila Cabello",
  "Creedence Clearwater Revival",
  "Cheat Codes",
  "Convolk",
  "DaBaby",
  "David Guetta",
  "Demi Lovato",
  "Drake",
  "Dua Lipa",
  "Elton John",
  "Eminem",
  "Flume",
  "Frank Ocean",
  "Franz Ferdinand",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Green Day",
  "Jason Derulo",
  "Jeremy Zucker",
  "Katy Perry",
  "Kesha",
  "Khalid",
  "Lil Aaron",
  "Lil Wayne",
  "Loote",
  "Loud Luxury",
  "Lucas & Steve",
  "Maroon 5",
  "Marshmello",
  "Martin Garrix",
  "Notorious BIG",
  "Owl City",
  "Pink",
  "Post Malone",
  "Rolling Stones",
  "Sia",
  "Snoop Dogg",
  "Sum 41",
  "T-Pain",
  "The Beatles",
  "Tom Petty",
  "Travis Scott",
  "Weezer",
  "Wiz Khalifa",
];

const mix6Artists = [
  '100 Gecs',
'AJR',
'All American Rejects',
'Anderson Paak',
'Andy Grammer',
'Avicii',
'Bebe Rexha',
'Big Sean',
'Blackbear',
'Blink 182',
'Bruno Mars',
'Call Me Karizma',
'Camila Cabello',
'Chainsmokers',
'Cheat Codes',
'Convolk',
'DaBaby',
'David Guetta',
'Demi Lovato',
'Drake',
'Eminem',
'Frank Ocean',
'Future',
'G Eazy',
'Galantis',
'Goody Grace',
'Iamsu',
'Illenium',
'Jay Sean',
'Jeremy Zucker',
'Katy Perry',
'Kesha',
'Khalid',
'Kid Cudi',
'Lil Dicky',
'Lil Peep',
'Lil Pump',
'Lil Wayne',
'Lizzo',
'Loote',
'Loud Luxury',
'Lucas & Steve',
'Marc E Bassy',
'Marshmello',
'Martin Garrix',
'MGK',
'Notorious BIG',
'Pink',
'Post Malone',
'Sia',
'Snoop Dogg',
'Sum 41',
'SZA',
'T Pain',
'The Weeknd',
'Timeflies',
'Ty Dolla Sign',
'Weezer',
'Wiz Khalifa',
'Yo Gotti',
]
const mix7Artists = [

]

const mix8Artists = [
  "50 Cent",
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Avicii",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Camila Cabello",
  "Cardi B",
  "Chainsmokers",
  "Chance The Rapper",
  "Cheat Codes",
  "Clean Bandit",
  "Creedence Clearwater Revival",
  "DaBaby",
  "Drake",
  "Eminem",
  "Future",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Iamsu",
  "J Cole",
  "Jason Derulo",
  "Jay Sean",
  "Jeremy Zucker",
  "Justin Bieber",
  "Katy Perry",
  "Kesha",
  "Kid Cudi",
  "KYLE",
  "Lil Aaron",
  "Lil Pump",
  "Lil Uzi Vert",
  "Lil Wayne",
  "Lil Yachty",
  "Loote",
  "Loud Luxury",
  "Lucas & Steve",
  "Machine Gun Kelly",
  "Martin Garrix",
  "Michael Jackson",
  "NOTD",
  "Notorious BIG",
  "P-Lo",
  "Pink",
  "Post Malone",
  "Sean Paul",
  "Sia",
  "Snoop Dogg",
  "SZA",
  "The Weeknd",
  "Tom Petty",
  "Travis Scott",
  "Trevor Daniel",
  "Trinidad James",
  "Usher",
  "Wiz Khalifa",
  "YBN Nahmir",
  "Yo Gotti",
];

const mix9Artists = [
  
]

const mix10Artists = [
  "100 Gecs",
  "3Oh!3",
  "50 Cent",
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Anderson Paak",
  "Ariana Grande",
  "Avicii",
  "Blackbear",
  "Blink 182",
  "Camila Cabello",
  "Creedence Clearwater Revival",
  "Chainsmokers",
  "Cheat Codes",
  "Clean Bandit",
  "Elton John",
  "Eminem",
  "Fetty Wap",
  "Flume",
  "Frank Ocean",
  "Future",
  "G Eazy",
  "Galantis",
  "Goody Grace",
  "Green Day",
  "Illenium",
  "J Cole",
  "Jay Sean",
  "Kanye West",
  "Kesha",
  "Kygo",
  "Lauv",
  "Lil Aaron",
  "Lil Pump",
  "Lil Wayne",
  "Lil Yachty",
  "Loote",
  "Mac Miller",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Michael Jackson",
  "Mike Williams",
  "NOTD",
  "Notorious BIG",
  "Owl City",
  "Post Malone",
  "The Proclaimers",
  "Rihanna",
  "Sage The Gemini",
  "Selena Gomez",
  "Shakira",
  "Sia",
  "Tom Petty",
  "Travis Scott",
  "Usher",
  "Yo Gotti",
  "Young Dro",
];

const mix11Artists = [
  "100 Gecs",
  "50 Cent",
  "AJR",
  "Aloe Blacc",
  "Anderson Paak",
  "Ariana Grande",
  "Avicii",
  "Backstreet Boys",
  "Bastille",
  "Bebe Rexha",
  "Black Eyed Peas",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Creedence Clearwater Revival",
  "Chainsmokers",
  "Chance The Rapper",
  "Charlie XCX",
  "Cher",
  "Chris Brown",
  "Chumbawamba",
  "Cyndi Lauper",
  "Clean Bandit",
  "Cobra Starship",
  "DaBaby",
  "DJ Snake",
  "Drake",
  "Dua Lipa",
  "Eminem",
  "Felix Jaehn",
  "Fetty Wap",
  "Fifth Harmony",
  "Galantis",
  "Goody Grace",
  "J Cole",
  "Jason Derulo",
  "Jeremy Zucker",
  "Journey",
  "Kanye West",
  "Katy Perry",
  "Kesha",
  "Khalid",
  "Kygo",
  "Lady Gaga",
  "Lil Dicky",
  "Lil Peep",
  "Lil Yachty",
  "Lizzo",
  "Loud Luxury",
  "Louis The Child",
  "LZRD",
  "Mac Miller",
  "Major Lazer",
  "Martin Garrix",
  "Martin Solveig",
  "Machine Gun Kelly",
  "Michael Jackson",
  "Mike Posner",
  "NOTD",
  "P-Lo",
  "Post Malone",
  "Preme",
  "Quinn XCII",
  "Rihanna",
  "Sam Feldt",
  "Sean Paul",
  "Sia",
  "Social House",
  "Survivor",
  "The Wanted",
  "The Weeknd",
  "Tiesto",
  "Tom Petty",
  "Tones and I",
  "Tove Lo",
  "Travis Scott",
  "Ty Dolla Sign",
  "Uncle Kracker",
  "Usher",
  "Yo Gotti",
];

const mix12Artists = [
  "24kGoldn",
  "50 Cent",
  "AJR",
  "All American Rejects",
  "Aloe Blacc",
  "Anderson Paak",
  "Astrid S",
  "Avicii",
  "Bastille",
  "Bebe Rexha",
  "Billie Eilish",
  "Black Eyed Peas",
  "Blackbear",
  "Blink 182",
  "Bruno Mars",
  "Cardi B",
  "Chainsmokers",
  "Chance The Rapper",
  "Charlie XCX",
  "Cheat Codes",
  "Cher",
  "Chris Brown",
  "David Guetta",
  "Diana Ross",
  "Drake",
  "Dua Lipa",
  "Eiffel 65",
  "Fifth Harmony",
  "G Eazy",
  "Galantis",
  "Green Day",
  "Iamsu",
  "Illenium",
  "Jason Derulo",
  "Jay Sean",
  "Kanye West",
  "Katy Perry",
  "Khalid",
  "Kid Cudi",
  "Kid Ink",
  "Lil Pump",
  "Lil Uzi Vert",
  "Lil Wayne",
  "Lil Yachty",
  "Loote",
  "Louis The Child",
  "Lucas & Steve",
  "LZRD",
  "Martin Garrix",
  "Michael Jackson",
  "Nicki Minaj",
  "NOTD",
  "Owl City",
  "Post Malone",
  "Preme",
  "Rihanna",
  "Sam Feldt",
  "Sum 41",
  "The Beatles",
  "Topic",
  "Travis Scott",
  "Trinidad James",
  "Ty Dolla Sign",
  "Weezer",
  "Wiz Khalifa",
];

const mix13Artists = [
  "3Oh!3",
  "50 Cent",
  "Aloe Blacc",
  "Anderson Paak",
  "Andy Grammer",
  "Avicii",
  "Bastille",
  "The Beatles",
  "Bebe Rexha",
  "Bruno Mars",
  "Bryce Vine",
  "Call Me Karizma",
  "Camila Cabello",
  "Chainsmokers",
  "Chance The Rapper",
  "Charlie XCX",
  "Cheat Codes",
  "Chris Brown",
  "Clean Bandit",
  "Cobra Starship",
  "Diana Ross",
  "Ed Sheeran",
  "Eiffel 65",
  "Eminem",
  "Fetty Wap",
  "Galantis",
  "Green Day",
  "Iamsu",
  "J Cole",
  "Jason Derulo",
  "Kanye West",
  "Katy Perry",
  "Kesha",
  "Kygo",
  "Lady Gaga",
  "Lil Pump",
  "Lil Wayne",
  "Lil Yachty",
  "Lizzo",
  "Loote",
  "Louis The Child",
  "Lukas Graham",
  "Makeout",
  "Maroon 5",
  "Martin Garrix",
  "Machine Gun Kelly",
  "Migos",
  "Mike Posner",
  "Nicki Minaj",
  "NOTD",
  "Owl City",
  "P-Lo",
  "Pink",
  "Post Malone",
  "Pusha T",
  "Quavo",
  "Quinn XCII",
  "Sam Feldt",
  "T-Pain",
  "The Beatles",
  "The Him",
  "The Neighbourhood",
  "The Proclaimers",
  "Tones and I",
  "Topic",
  "Travis Scott",
  "Trinidad James",
  "Uncle Kracker",
  "Wallpaper.",
  "Wiz Khalifa",
];

const mix14Artists = [
  '24k Goldn',
'3Oh!3',
'50 Cent',
'Akon',
'Aloe Blacc',
'Anderson Paak',
'Ariana Grande',
'Avicii',
'Backstreet Boys',
'Bebe Rexha',
'Big Sean',
'Blackbear',
'Bryce Vine',
'Camila Cabello',
'CCR',
'Chainsmokers',
'Cheat Codes',
'Chris Brown',
'Clean Bandit',
'Cobra Starship',
'Cyndi Lauper',
'DJ Snake',
'Dua Lipa',
'Ed Sheeran',
'Eiffel 65',
'Elton John',
'Fetty Wap',
'Future',
'Galantis',
'Green Day',
'J Cole',
'Jason Derulo',
'Kanye West',
'Katy Perry',
'Kesha',
'Kid Cudi',
'Kygo',
'Lil Pump',
'Lil Wayne',
'Lizzo',
'Louis The Child',
'Lukas Graham',
'Major Lazer',
'Makeout',
'MGK',
'Migos',
'Mike Posner',
'Nicki Minaj',
'NOTD',
'P-Lo',
'Pink',
'Post Malone',
'Pusha T',
'Quavo',
'Sean Paul',
'Shakira',
'Snoop Dogg',
'The Beatles',
'The Game',
'The Him',
'The Neighborhood',
'The Proclaimers',
'Tom Petty',
'Tones and I',
'Travis Scott',
'Trinidad James',
'Usher',
'Wallpaper.',
'Whitney Houston',
'Wiz Khalifa',
'Yo Gotti',
]

const mix15Artists = [
  '24k Goldn',
'50 Cent',
'AJR',
'All American Rejects',
'Anderson Paak',
'Ariana Grande',
'Bee Gees',
'Black Eyed Peas',
'Blackbear',
'Bruno Mars',
'Camila Cabello',
'Cardi B',
'CCR',
'Chainsmokers',
'Chance The Rapper',
'Charlie XCX',
'Cheat Codes',
'Chris Brown',
'Cindi Lauper',
'Clean Bandit',
'DaBaby',
'Eminem',
'Future',
'G Eazy',
'Galantis',
'Iamsu',
'J Cole',
'Jay Sean',
'Kanye West',
'Kesha',
'Kid Cudi',
'Kid Ink',
'Kygo',
'Lauv',
'Lil Dicky',
'Lil Peep',
'Lil Pump',
'Lil Uzi Vert',
'Lil Wayne',
'Lil Yachty',
'Loud Luxury',
'Mac Miller',
'Makeout',
'Maroon 5',
'Migos',
'Mike Posner',
'Notorious BIG',
'Pink',
'Post Malone',
'Sia',
'Snoop Dogg',
'Sum 41',
'Survivor',
'T Pain',
'The Neighborhood',
'Tom Petty',
'Travis Scott',
'Trevor Daniel',
'Trinidad James',
'Weezer',
'Whitney Houston',
'Wiz Khalifa',
'Yo Gotti',
'Young Dro',
]

const mix16Artists = [
  'AJR',
'Akon',
'All American Rejects',
'Aloe Blacc',
'Ariana Grande',
'Avicii',
'Bastille',
'Black Eyed Peas',
'Blink 182',
'Brakence',
'Bruno Mars',
'Bryce Vine',
'Camila Cabello',
'Chainsmokers',
'Cheat Codes',
'Chelsea Cutler',
'Chumbawamba',
'Cobra Starship',
'Cyndi Lauper',
'Disclosure',
'DJ Snake',
'Don Diablo',
'Eiffel 65',
'Elton John',
'Felix Jaehn',
'Fetty Wap',
'G Eazy',
'Galantis',
'Green Day',
'Halsey',
'Harry Styles',
'Hoodie Allen',
'Jason Derulo',
'Jay Sean',
'Kanye West',
'Katy Perry',
'Kesha',
'Khalid',
'Kid Cudi',
'Kygo',
'Lauv',
'Lil Dicky',
'Lil Wayne',
'Lukas Graham',
'Major Lazer',
'Martin Garrix',
'Matoma',
'Mike Posner',
'NOTD',
'Owl City',
'Pink',
'Post Malone',
'Que',
'Quinn XCII',
'Rihanna',
'Sam Feldt',
'Sam Smith',
'Sean Paul',
'Shawn Mendes',
'Survivor',
'T Pain',
'Taylor Swift',
'The Beatles',
'The Fray',
'The Game',
'The Him',
'Tiesto',
'Tove Lo',
'Travis Scott',
'Trevor Daniel',
'Usher',
'Whitney Houston',
'Wiz Khalifa',
'Young Dro',
]

const mix17Artists = [
  'AJR',
'All American Rejects',
'Aloe Blacc',
'Anderson Paak',
'Ariana Grande',
'Avicii',
'Backstreet Boys',
'Bastille',
'Blackbear',
'Blink 182',
'Brakence',
'Bruno Mars',
'Camila Cabello',
'CCR',
'Chainsmokers',
'Cheat Codes',
'Chumbawamba',
'Cobra Starship',
'Coldplay',
'Cyndi Lauper',
'David Guetta',
'Dua Lipa',
'Ed Sheeran',
'Eiffel 65',
'Elton John',
'Frank Ocean',
'Galantis',
'Halsey',
'Harry Styles',
'Jason Derulo',
'Jon Bellion',
'Journey',
'Justin Bieber',
'Kanye West',
'Katy Perry',
'Kesha',
'Khalid',
'Kygo',
'Lauv',
'Lil Dicky',
'Lil Wayne',
'Loote',
'Lukas Graham',
'Martin Solveig',
'MGK',
'Miguel',
'Mike Posner',
'Nicki Minaj',
'Owl City',
'Pink',
'Post Malone',
'Que',
'Quinn XCII',
'Rick Springfield',
'Rihanna',
'Sean Paul',
'Shakira',
'Social House',
'Survivor',
'The Beatles',
'The Game',
'The Him',
'The Neighbourhood',
'The Proclaimers',
'TI',
'Tiesto',
'Travis Scott',
'Trevor Daniel',
'Uncle Kracker',
'Usher',
]

const mix1 = {
  title: "mix1",
  artists: mix1Artists,
  firstArtist: ["Katy Perry"],
};
const mix2 = {
  title: "mix2",
  artists: mix2Artists,
  firstArtist: ["Aloe Blacc", "Avicii"],
};
const mix3 = {
  title: "mix3",
  artists: mix3Artists,
  firstArtist: ["Lil Dicky"],
};
const mix4 = {
  title: "mix4",
  artists: mix4Artists,
  firstArtist: ["Notorious BIG"],
};
const mix5 = {
  title: "mix5",
  artists: mix5Artists,
  firstArtist: ["Cheat Codes", "Demi Lovato"],
};
const mix6 = {
  title: "mix6",
  artists: mix6Artists,
  firstArtist: ["Cheat Codes"],
};
const mix7 = {
  title: "mix7",
  artists: mix7Artists,
  firstArtist: ["Pink"],
};
const mix8 = {
  title: "mix8",
  artists: mix8Artists,
  firstArtist: ["Usher"],
};
const mix9 = {
  title: "mix9",
  artists: mix9Artists,
  firstArtist: ["Kesha"],
};
const mix10 = {
  title: "mix10",
  artists: mix10Artists,
  firstArtist: ["Chainsmokers"],
};
const mix11 = {
  title: "mix11",
  artists: mix11Artists,
  firstArtist: ["Post Malone"],
};
const mix12 = {
  title: "mix12",
  artists: mix12Artists,
  firstArtist: ["Galantis"],
};
const mix13 = {
  title: "mix13",
  artists: mix13Artists,
  firstArtist: ["Migos"],
};
const mix14 = {
  title: "mix14",
  artists: mix14Artists,
  firstArtist: ["Ariana Grande"],
};
const mix15 = {
  title: "mix15",
  artists: mix15Artists,
  firstArtist: ["Kanye West"],
};
const mix16 = {
  title: "mix16",
  artists: mix16Artists,
  firstArtist: ["Lauv"],
};
const mix17 = {
  title: "mix17",
  artists: mix17Artists,
  firstArtist: ["Harry Styles"],
};


export const mixes = [
  mix1,
  mix2,
  mix3,
  mix4,
  mix5,
  mix6,
  mix7,
  mix8,
  mix9,
  mix10,
  mix11,
  mix12,
  mix13,
  mix14,
  mix15,
  mix16,
  mix17,
];
